-- 已废弃（DEPRECATED）：D1 结构已迁移至 apps/worker/migrations/。
-- V2 数据模型（迁移 0001~0003）是唯一结构来源：
--   0001_init.sql      本项目 v1 通用表
--   0002_gateway.sql   吸收蓝本的账号池 / 网关计量表
--   0003_checkin.sql   自动签到配置与日志
-- 不要在本文件重复维护表结构，避免与 migrations 冲突。
-- 应用：wrangler d1 migrations apply drawing-workbench --local|--remote
